# Changes here will be overwritten by Copier
_commit: v2.0.5
_src_path: gh:lincc-frameworks/python-project-template
author_email: jfc20@uw.edu
author_name: John Franklin Crenshaw
create_example_module: true
custom_install: true
enforce_style:
- black
- isort
failure_notification: []
include_benchmarks: true
include_docs: true
include_notebooks: true
mypy_type_checking: basic
package_name: cwfs
project_license: MIT
project_name: cwfs
project_organization: jfcrenshaw
python_versions:
- '3.11'
- '3.12'
- '3.13'
